name: CID5

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Ngrog Token'
        required: true
      loca:
        description: 'Ngrog region: us - eu - ap - au - sa - jp - in '
        required: true
        default: 'us'
jobs:
 build:

    runs-on: windows-latest
    timeout-minutes: 4000

    steps:
    - name: Download
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/phamduy091/TESTNEW/RDP/start.bat -OutFile start.bat    
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken ${{ github.event.inputs.authcode }}
      env:
        NGROK_AUTH_TOKEN: ${{ github.event.inputs.authcode }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/phamduy091/TESTNEW/RDP/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
