name: RDP1

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Ngrog Token'
        required: true
      loca:
        description: 'Ngrog region: us - eu - ap - au - sa - jp - in '
        required: true
        default: 'eu'
jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Download
      run: Invoke-WebRequest https://cdn.jsdelivr.net/gh/rialms/rdp@master/dl/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
      
